TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = HTTPServer.cpp \
	JSONObject.cpp

INCLUDES += $(GENERAL_INC)


.PHONY: all
all: $(OBJECTS)


.PHONY: clean
clean: cmn-clean
	

	
include $(TOPLEVEL)/rules.mk




