--- MediaHarmony-orig/Makefile	2007-11-06 10:07:22.000000000 +0000
+++ Makefile	2008-03-26 23:37:57.000000000 +0000
@@ -13,7 +13,16 @@
 SAMBA_SOURCE	= $(SAMBA_DIR)source
 SHLIBEXT	= so
 OBJEXT		= o 
-FLAGS		=  $(CFLAGS) -Iinclude -I$(SAMBA_SOURCE)/include -I$(SAMBA_SOURCE)/popt -I$(SAMBA_SOURCE)/ubiqx -I$(SAMBA_SOURCE)/smbwrapper  -I. $(CPPFLAGS) -I$(SAMBA_SOURCE) -fPIC
+FLAGS       =  $(CFLAGS) $(CPPFLAGS) -fPIC \
+        -Iinclude -I$(SAMBA_SOURCE)/include \
+        -I$(SAMBA_SOURCE)/popt  \
+        -I$(SAMBA_SOURCE)/lib/replace  \
+        -I$(SAMBA_SOURCE)/lib/talloc  \
+        -I$(SAMBA_SOURCE)/tdb/include  \
+        -I$(SAMBA_SOURCE)/smbwrapper \
+        -I$(SAMBA_SOURCE)/librpc \
+        -I$(SAMBA_SOURCE) -I.
+
 
 
 prefix		= /usr/local/samba
@@ -24,6 +33,7 @@
 
 .PHONY: default
 default: media_harmony.so mh_full_audit.so media_many.so media_link.so mxf_harmony.so test_mxf_essence
+test: media_harmony.so
 
 
 # mxf_harmony
@@ -79,7 +89,6 @@
 	$(CC) $(LDSHFLAGS) $(LDFLAGS) mh_full_audit.o -o mh_full_audit.so 
 
 
-
 install: default
 	$(INSTALLCMD) -d $(VFS_LIBDIR)
 	$(INSTALLCMD) -m 755 *.$(SHLIBEXT) $(VFS_LIBDIR)
