TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = FFmpegEncoder.cpp \
	FFmpegDecoder.cpp

INCLUDES += $(GENERAL_INC) $(INGEX_COMMON_INC) $(INGEX_STUDIO_FFMPEG_INC)



.PHONY: all
all: $(OBJECTS)

	
.PHONY: clean
clean: cmn-clean
	

	
include $(TOPLEVEL)/rules.mk

