TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = PostgresDatabase.cpp \
	DatabaseThings.cpp \
	RecorderDatabase.cpp

INCLUDES += $(GENERAL_INC)


.PHONY: all
all: $(OBJECTS)


.PHONY: clean
clean: cmn-clean
	

	
include $(TOPLEVEL)/rules.mk




