// dvrecorder.idl

// Copyright (c) 2005. British Broadcasting Corporation. All Rights Reserved.

#ifndef DVRECORDER_IDL
#define DVRECORDER_IDL

#pragma prefix "bbc.co.uk"


module ProdAuto {

/**
	Interface for a file-based DV Recorder.  It deals with one input stream
	and can only make one recording at a time.
*/
	interface dvRecorder
	{
		enum ReturnCode { OK, FAILED };
		enum StatusCode { READY, RECORDING, PROBLEM };
		typedef string Timecode;

		/// Start recording the incoming DV stream.
		/// @param filename The supplied value is used as the beginning
		/// of the filename.  The return value is a full URL for the
		/// file.
		/// @param in_time Timecode of the first frame in the file.
		/// @return Indication of success or failure.
		ReturnCode StartRecording(inout string filename, out Timecode in_time);

		/// Stop recording the incoming DV stream.
		/// @param out_time Timecode of the frame after the last frame in the file.
		/// @return Indication of success or failure.
		ReturnCode StopRecording(out Timecode out_time);

		/// Get status of the recorder
		StatusCode Status();
	};
};


#endif  // #ifndef DVRECORDER_IDL

