// processor.idl

// Copyright (c) 2005. British Broadcasting Corporation. All Rights Reserved.

#ifndef processor_idl
#define processor_idl

#pragma prefix "bbc.co.uk"


module ProdAuto {

/**
	Interface for a content processor.
*/
	interface Processor
	{
		typedef unsigned long ProcessID;
		enum StatusCode { RUNNING, DONE, FAILED, UNKNOWN };

		/// Start processing, using the supplied arguments.
		/// @return Non-zero process identifier on success, zero otherwise.
		ProcessID Process(in string args);

		/// Get status of identified process
		StatusCode Status(in ProcessID pid);
	};
};


#endif  // #ifndef processor_idl

