// RecorderObserver.idl

// Copyright (c) 2006. British Broadcasting Corporation. All Rights Reserved.

#ifndef RecorderObserver_idl
#define RecorderObserver_idl

#pragma prefix "bbc.co.uk"

module ProdAuto
{
};

#endif //#ifndef RecorderObserver_idl

