// Source.idl

// Copyright (c) 2006. British Broadcasting Corporation. All Rights Reserved.

#ifndef Source_idl
#define Source_idl

#pragma prefix "bbc.co.uk"

#include "defs.idl"

module ProdAuto
{
    /**
    A means of identifying the source of a recorded track.
    In the MXF model, the source might be a tape or a live ("recording") source.
    The numeric IDs have been commented out as we don't need these in our CORBA
    messages.
    */
	struct Source
	{
		//UMID package_id;
		string package_name;
		//TrackId track_id;
		string track_name;
	};
	typedef sequence<Source> SourceList;
};

#endif //#ifndef Source_idl
