/*
 * $Id: Track.idl,v 1.1 2007/09/11 14:08:22 stuart_hc Exp $
 *
 * Track structure definition.
 *
 * Copyright (C) 2006  British Broadcasting Corporation.
 * All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

#ifndef Track_idl
#define Track_idl

#pragma prefix "bbc.co.uk"

#include "defs.idl"
#include "Source.idl"

module ProdAuto
{
	// An individual track
	enum TrackType { AUDIO, VIDEO };
	struct Track
	{
		TrackType type;
		TrackId id;
		string name;
		//Rational edit_rate;
		//origin = 0
        boolean has_source;
		Source src;
	};
	typedef sequence<Track> TrackList;
};

#endif //#ifndef Track_idl
