TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = RecorderException.cpp \
	Logging.cpp \
	Threads.cpp \
	Utilities.cpp \
	DirectoryWatch.cpp \
	Config.cpp \
	Timing.cpp \
	FileLock.cpp \
	ByteArray.cpp



.PHONY: all
all: $(OBJECTS)


.PHONY: clean
clean: cmn-clean
	
	

include $(TOPLEVEL)/rules.mk


