TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = InfaxAccess.cpp \
	LocalInfaxAccess.cpp \
	LocalInfaxDatabase.cpp

INCLUDES += $(DATABASE_INC) $(GENERAL_INC) $(VTR_INC) $(DVS_INC)


.PHONY: all
all: $(OBJECTS)


.PHONY: clean
clean: cmn-clean
	

	
include $(TOPLEVEL)/rules.mk




