TOPLEVEL = ..
include $(TOPLEVEL)/vars.mk


SOURCES = Cache.cpp

INCLUDES += $(GENERAL_INC) $(DATABASE_INC)


.PHONY: all
all: $(OBJECTS)


.PHONY: clean
clean: cmn-clean
	

	
include $(TOPLEVEL)/rules.mk




